version: "3"

services:
  eds-app:
    image: flask_image
    container_name: flask_image
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./data/log:/code/log
    environment:
      - FLASK_DEBUG=True