version: "3"

services:
  web:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data/log:/code/data/log
      - ./data/db:/code/data/db
    environment:
      - FLASK_LOG=/code/data/log/flask.log
      - FLASK_DEBUG=True
      - DATABASE=/code/data/db/DB.db